#pragma once
#include <M5Dial.h>

// ---------------------------------------------------------------------------
// Sounds.h — Buzzer tone sequences for mission events
//
// Each sequence is an array of {frequency_hz, duration_ms} pairs.
// frequency = 0 means a silent pause.
// Call playSound(sequence, length, volume, name, extIndex) to play.
// When extIndex > 0 and the external AudioPlayer callback is set,
// the .mp3 file is played instead of the buzzer (non-blocking).
// See AudioIndex.h for the full SD card file map.
// ---------------------------------------------------------------------------

// External AudioPlayer SD card indices for mission sounds (002-012)
static constexpr uint16_t EXT_BADGE_SCAN       = 2;
static constexpr uint16_t EXT_MISSION_START    = 3;
static constexpr uint16_t EXT_LOCATION_VISIT   = 4;
static constexpr uint16_t EXT_MISSION_COMPLETE = 5;
static constexpr uint16_t EXT_TIMEOUT          = 6;
static constexpr uint16_t EXT_ERROR            = 7;
static constexpr uint16_t EXT_MISSION_SCRUBBED = 8;
static constexpr uint16_t EXT_BADGE_COOLDOWN   = 9;
static constexpr uint16_t EXT_BADGE_REMOVED    = 10;
static constexpr uint16_t EXT_RESET            = 11;
static constexpr uint16_t EXT_SERVER_RETRY     = 12;

// Callback for external AudioPlayer — set via setExtAudioPlayer() in setup()
typedef bool (*ExtAudioPlayFn)(uint16_t index);
static ExtAudioPlayFn _extAudioPlay = nullptr;
inline void setExtAudioPlayer(ExtAudioPlayFn fn) { _extAudioPlay = fn; }

struct Note {
  uint16_t freq;
  uint16_t duration;
};

// Play a tone sequence (blocking buzzer, or non-blocking AudioPlayer if ext index provided)
inline void playSound(const Note* notes, uint8_t count, uint8_t volume = 255, const char* name = nullptr, uint16_t extIndex = 0) {
  if (name) Serial.printf("[AUDIO] %lums  Playing: %s (%d notes, vol %d, ext %d)\n", millis(), name, count, volume, extIndex);
  else      Serial.printf("[AUDIO] %lums  Playing: unnamed (%d notes, vol %d, ext %d)\n", millis(), count, volume, extIndex);

  // Prefer external AudioPlayer when available
  if (extIndex > 0 && _extAudioPlay && _extAudioPlay(extIndex)) {
    return;
  }

  // Fallback: internal buzzer (blocking)
  M5Dial.Speaker.setVolume(volume);
  for (uint8_t i = 0; i < count; i++) {
    if (notes[i].freq == 0) {
      delay(notes[i].duration);
    } else {
      M5Dial.Speaker.tone(notes[i].freq, notes[i].duration);
      delay(notes[i].duration);
    }
  }
  M5Dial.Speaker.stop();
}

// ---------------------------------------------------------------------------
// BADGE SCANNED — single sharp blip
// ---------------------------------------------------------------------------
// Generated by Piezo Tone Architect
const Note SND_BADGE_SCAN[] = {
  {800, 80},   // Accept
  {1200, 80},  // Accept
  {1600, 200}, // Accept
};
#define SND_BADGE_SCAN_LEN (sizeof(SND_BADGE_SCAN) / sizeof(Note))

// ---------------------------------------------------------------------------
// MISSION CARD SCANNED — 5-note power sweep C4 -> C6
// ---------------------------------------------------------------------------
const Note SND_MISSION_START[] = {
  {523, 70},   // C5
  {659, 70},   // E5
  {784, 90},   // G5
  {988, 110},  // B5
  {1046, 220}, // C6
  {0, 45},     // REST
  {784, 60},   // G5
  {988, 60},   // B5
  {1046, 260}, // C6
};
#define SND_MISSION_START_LEN (sizeof(SND_MISSION_START) / sizeof(Note))

// ---------------------------------------------------------------------------
// LOCATION VISITED — triple high chirp at E6
// ---------------------------------------------------------------------------
const Note SND_LOCATION_VISIT[] = {
  {1319, 70},   // E6
  {0,    25},
  {1319, 70},   // E6
  {0,    25},
  {1319,120},   // E6
};
#define SND_LOCATION_VISIT_LEN (sizeof(SND_LOCATION_VISIT) / sizeof(Note))

// ---------------------------------------------------------------------------
// CONFIRM PLAYERS — quick switch/zoom stinger
// ---------------------------------------------------------------------------
const Note SND_CONFIRM_PLAYERS[] = {
  {600, 50},   // Switch 50ms
  {0,   25},   // REST 25ms
  {1200, 50},  // Switch 50ms
  {0,   25},   // REST 25ms
  {800, 25},   // Zoom 25ms
  {1000, 25},  // Zoom 25ms
  {1400, 25},  // Zoom 25ms
  {1800, 50},  // Land 50ms
  {0,   25},   // REST 25ms
  {1400, 75},  // Ready 75ms
};
#define SND_CONFIRM_PLAYERS_LEN (sizeof(SND_CONFIRM_PLAYERS) / sizeof(Note))

// ---------------------------------------------------------------------------
// CONFIRM SELECT — tighter click/chime for YES/NO tap
// (based on GTA text-style quick chirp)
// ---------------------------------------------------------------------------
const Note SND_CONFIRM_SELECT[] = {
  {1400, 40},
  {1800, 40},
  {0,    30},
  {1600, 60},
};
#define SND_CONFIRM_SELECT_LEN (sizeof(SND_CONFIRM_SELECT) / sizeof(Note))

// ---------------------------------------------------------------------------
// ADMIN ACCEPT — short positive ping for known-tag scans
// (based on Discord ping style)
// ---------------------------------------------------------------------------
const Note SND_ADMIN_ACCEPT[] = {
  {1200, 40},
  {0,    20},
  {1600, 80},
};
#define SND_ADMIN_ACCEPT_LEN (sizeof(SND_ADMIN_ACCEPT) / sizeof(Note))

// ---------------------------------------------------------------------------
// INFO CHIME — gentle informational cue
// (based on achievement-style two-step tone)
// ---------------------------------------------------------------------------
const Note SND_INFO_CHIME[] = {
  {880,  90},
  {0,    40},
  {988, 110},
};
#define SND_INFO_CHIME_LEN (sizeof(SND_INFO_CHIME) / sizeof(Note))

// ---------------------------------------------------------------------------
// STATE CHANGE — lightweight UI transition chirp
// ---------------------------------------------------------------------------
const Note SND_STATE_CHANGE[] = {
  {700, 40},
  {0,   20},
  {950, 55},
};
#define SND_STATE_CHANGE_LEN (sizeof(SND_STATE_CHANGE) / sizeof(Note))

// ---------------------------------------------------------------------------
// MISSION COMPLETE — custom sequence from espboards.dev
// D5, C5, A#4, D5, C5, A#4, D5, C5, A#4, G#4 — all 125ms
// ---------------------------------------------------------------------------
const Note SND_MISSION_COMPLETE[] = {
  {523, 75},   // C5 75ms
  {659, 75},   // E5 75ms
  {784, 75},   // G5 75ms
  {1046, 75},  // C6 75ms
  {0, 50},     // REST 50ms
  {1046, 75},  // C6 75ms
  {1318, 75},  // E6 75ms
  {1568, 200}, // G6 200ms
};
#define SND_MISSION_COMPLETE_LEN (sizeof(SND_MISSION_COMPLETE) / sizeof(Note))

// ---------------------------------------------------------------------------
// MISSION TIMEOUT — slow sad descent F4 -> C#4 -> G3
// ---------------------------------------------------------------------------
const Note SND_TIMEOUT[] = {
  {349, 300},   // F4
  {0,    60},
  {277, 300},   // C#4
  {0,    60},
  {196, 500},   // G3
};
#define SND_TIMEOUT_LEN (sizeof(SND_TIMEOUT) / sizeof(Note))

// ---------------------------------------------------------------------------
// ERROR / INVALID SCAN — rapid 3x low harsh buzz at 200Hz
// ---------------------------------------------------------------------------
const Note SND_ERROR[] = {
  {200,  80},
  {0,    30},
  {200,  80},
  {0,    30},
  {200,  80},
};
#define SND_ERROR_LEN (sizeof(SND_ERROR) / sizeof(Note))

// ---------------------------------------------------------------------------
// BADGE SCRUBBED — played when GM scrubs an active mission
// ---------------------------------------------------------------------------
const Note SND_MISSION_SCRUBBED[] = {
  {600, 150},
  {0,    40},
  {400, 150},
  {0,    40},
  {200, 400},
};
#define SND_MISSION_SCRUBBED_LEN (sizeof(SND_MISSION_SCRUBBED) / sizeof(Note))

// ---------------------------------------------------------------------------
// BADGE ON COOLDOWN — played when a blocked/scrubbed badge is scanned
// ---------------------------------------------------------------------------
// Generated by Piezo Tone Architect
const Note SND_BADGE_COOLDOWN[] = {
  {400, 30},  // Sweep
  {450, 30},  // Sweep
  {500, 30},  // Sweep
  {550, 30},  // Sweep
  {600, 30},  // Sweep
  {650, 30},  // Sweep
  {700, 30},  // Sweep
  {750, 30},  // Sweep
  {800, 30},  // Sweep
  {850, 30},  // Sweep
  {900, 30},  // Sweep
  {950, 30},  // Sweep
  {1000, 30}, // Sweep
  {950, 30},  // Sweep
  {900, 30},  // Sweep
  {850, 30},  // Sweep
  {800, 30},  // Sweep
  {750, 30},  // Sweep
  {700, 30},  // Sweep
  {650, 30},  // Sweep
  {600, 30},  // Sweep
  {550, 30},  // Sweep
  {500, 30},  // Sweep
  {450, 30},  // Sweep
};
#define SND_BADGE_COOLDOWN_LEN (sizeof(SND_BADGE_COOLDOWN) / sizeof(Note))

// ---------------------------------------------------------------------------
// BADGE REMOVED — player de-registered (descending two-tone drop)
// ---------------------------------------------------------------------------
// Generated by Music Maker
// BPM: 120
const Note SND_BADGE_REMOVED[] = {
  {1600, 75}, // Accept 75ms
  {1200, 75}, // Accept 75ms
  {800, 200}, // Accept 200ms
};
#define SND_BADGE_REMOVED_LEN (sizeof(SND_BADGE_REMOVED) / sizeof(Note))

// ---------------------------------------------------------------------------
// RESET — badge reset / full reset
// ---------------------------------------------------------------------------
const Note SND_RESET[] = {
  {523, 100},   // C5
  {0,    30},
  {330, 200},   // E4
};
#define SND_RESET_LEN (sizeof(SND_RESET) / sizeof(Note))

// ---------------------------------------------------------------------------
// SAFE CRACKER — exact-match confirm beep and proximity radar beeps
//
// playSafeConfirmTone()  : play when dial lands on the exact digit.
// playSafeProxTone(freq) : call each proximity interval; freq is computed by
//                          caller via map(dist, 1, 15, 1800, 500).
//                          SND_SAFE_PROX[0].freq is a placeholder only.
// ---------------------------------------------------------------------------
const Note SND_SAFE_CONFIRM[] = {
  {2200, 80},   // single sharp beep on exact match
};
#define SND_SAFE_CONFIRM_LEN (sizeof(SND_SAFE_CONFIRM) / sizeof(Note))
const uint8_t SND_SAFE_CONFIRM_VOL = 200;

const Note SND_SAFE_PROX[] = {
  {1000, 25},   // freq is overridden at runtime; tune duration here
};
#define SND_SAFE_PROX_LEN (sizeof(SND_SAFE_PROX) / sizeof(Note))
const uint8_t SND_SAFE_PROX_VOL = 180;

inline void playSafeConfirmTone() {
  Serial.printf("[AUDIO] %lums  Playing: SAFE_CONFIRM (freq %d, %dms)\n", millis(), SND_SAFE_CONFIRM[0].freq, SND_SAFE_CONFIRM[0].duration);
  M5Dial.Speaker.setVolume(SND_SAFE_CONFIRM_VOL);
  M5Dial.Speaker.tone(SND_SAFE_CONFIRM[0].freq, SND_SAFE_CONFIRM[0].duration);
}
inline void playSafeProxTone(int freq) {
  Serial.printf("[AUDIO] %lums  Playing: SAFE_PROX (freq %d, %dms)\n", millis(), freq, SND_SAFE_PROX[0].duration);
  M5Dial.Speaker.setVolume(SND_SAFE_PROX_VOL);
  M5Dial.Speaker.tone(freq, SND_SAFE_PROX[0].duration);
}

// ---------------------------------------------------------------------------
// SERVER SENDING — tones for the HTTP request lifecycle
//
// playSendingDot(i)       : ascending blip for dot i (0-2) in the animation.
// startSendHoldTone()     : call before a primary POST; stop with Speaker.stop().
// startResourceHoldTone() : call before a secondary resource POST (quieter).
// SND_SERVER_RETRY        : play between failed retry attempts via playSound().
//
// Hold tone duration must stay > HTTP_TIMEOUT — stopped manually on response.
// ---------------------------------------------------------------------------

// Dot animation — edit freq/duration per dot here
const Note SND_SENDING_DOTS[] = {
  {500, 280},   // dot 1
  {700, 280},   // dot 2
  {900, 280},   // dot 3
};
#define SND_SENDING_DOTS_LEN (sizeof(SND_SENDING_DOTS) / sizeof(Note))
const uint8_t SND_SENDING_DOTS_VOL = 200;

// Primary POST send tone — short blip before sending
// Generated by Music Maker
// BPM: 120
const Note SND_SERVER_HOLD[] = {
  {523, 75},   // C5 75ms
  {659, 75},   // E5 75ms
  {784, 75},   // G5 75ms
  {1046, 200}, // C6 200ms
};
#define SND_SERVER_HOLD_LEN (sizeof(SND_SERVER_HOLD) / sizeof(Note))
const uint8_t SND_SERVER_HOLD_VOL = 180;

// Secondary resource POST hold tone (quieter) — tune freq here
// Generated by Music Maker
// BPM: 120
const Note SND_RESOURCE_HOLD[] = {
  {523, 75},   // C5 75ms
  {659, 75},   // E5 75ms
  {784, 75},   // G5 75ms
  {1046, 200}, // C6 200ms
};
#define SND_RESOURCE_HOLD_LEN (sizeof(SND_RESOURCE_HOLD) / sizeof(Note))
const uint8_t SND_RESOURCE_HOLD_VOL = 130;

// Retry buzz — short low pulse between failed attempts
const Note SND_SERVER_RETRY[] = {
  {200, 200},
};
#define SND_SERVER_RETRY_LEN (sizeof(SND_SERVER_RETRY) / sizeof(Note))

inline void playSendingDot(int i) {
  Serial.printf("[AUDIO] %lums  Playing: SENDING_DOT_%d (freq %d)\n", millis(), i + 1, SND_SENDING_DOTS[i].freq);
  M5Dial.Speaker.setVolume(SND_SENDING_DOTS_VOL);
  M5Dial.Speaker.tone(SND_SENDING_DOTS[i].freq, SND_SENDING_DOTS[i].duration);
}
inline void startSendHoldTone() {
  Serial.printf("[AUDIO] %lums  Playing: SERVER_HOLD (freq %d)\n", millis(), SND_SERVER_HOLD[0].freq);
  M5Dial.Speaker.setVolume(SND_SERVER_HOLD_VOL);
  M5Dial.Speaker.tone(SND_SERVER_HOLD[0].freq, SND_SERVER_HOLD[0].duration);
}
inline void startResourceHoldTone() {
  Serial.printf("[AUDIO] %lums  Playing: RESOURCE_HOLD (freq %d)\n", millis(), SND_RESOURCE_HOLD[0].freq);
  M5Dial.Speaker.setVolume(SND_RESOURCE_HOLD_VOL);
  M5Dial.Speaker.tone(SND_RESOURCE_HOLD[0].freq, SND_RESOURCE_HOLD[0].duration);
}
